node('nodejs') {
  stage ('build'){
    script{
        sh 'echo COLUM TEST '
        openshiftBuild(buildConfig: 'nodejs-ex', showBuildLogs: 'true')
    }
  }
  stage 'deploy'
  openshiftDeploy(deploymentConfig: 'nodejs-ex')
}
