def GIT_BRANCH = 'master';
def GIT_REPO = "github.com/cfoskin/nodejs-ex.git";

pipeline {

  agent {
      label 'nodejs'
    }

  stages{

    stage('init'){
      steps {
        script {
                 sh 'echo INIT STAGE'
        }
      }
    }   

     stage('Set branch') {
      steps {
        script {
          try {
              timeout(time: 30, unit: 'SECONDS') {
                  GIT_BRANCH = input(
                      message: 'Set branch name:',
                      parameters: [
                          string(name: "branchName", description: "Branch to deploy, default is ${GIT_BRANCH}", defaultValue: "${GIT_BRANCH}")
                      ]
                  )
              }
          } catch(err) { } // catch the timeout error, proceed despite the error
        }
      }
    }

     stage('Clone') {
      steps {
        script {
          // dir('templates') {
          //   git branch:'master', url:"http://${CICD_GIT_REPO}", credentialsId: 'bitbucket-service-user'
          // }
          dir('oc-build') {
              git branch:"${GIT_BRANCH}", url:"https://${GIT_REPO}", credentialsId: 'bitbucket-service-user'
          }
        }
      }
    }


  }

}